<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */

/** @var \SomethingDigital\SidebarMinicart\ViewModel\SystemConfig $viewModel */
$viewModel = $block->getViewModel();
$secondsToDisplay = $viewModel->secondsToDisplay();
$autoDisplay = $viewModel->autoDisplayEnabled();
?>

<div data-block="minicart" class="minicart-wrapper">
    <a id="minicart-show" class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'"
       onclick="dataLayer.push({'event': 'minicart_show'}); ">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
        <div class="block block-minicart empty">
            <div id="minicart-content-wrapper" class="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
        <script>
            require(
                [
                    'jquery',
                    'jquery/ui',
                    'Magento_Ui/js/modal/modal'
                ],
                function($) {
                    var options = {
                        type: 'slide',
                        responsive: true,
                        innerScroll: false,
                        title: '',
                        buttons: [],
                        modalClass: 'minicart-modal',
                        trigger: '.minicart-wrapper .showcart',
                    };
                    $('#minicart-content-wrapper').modal(options);
                    $('.minicart-wrapper .showcart').on('click', function(e) {
                        e.preventDefault(); // prevent default behavior from redirecting customer
                    });
                }
            );
        </script>
        <script>
            /**
             * Checks if a variable is an HTML Element
             *
             * @param element
             * @returns {boolean}
             */
            function isElement(element) {
                return element instanceof Element || element instanceof HTMLDocument;
            }

            require(['Magento_Customer/js/customer-data'], function (customerData) {
                var cart = customerData.get('cart');
                var count = cart().summary_count;
                var displayOnAddToCart = ("<?= $autoDisplay ?>" === '1');

                if (displayOnAddToCart === false) {
                    return;
                }

                var secondsToDisplay = parseInt("<?= $secondsToDisplay ?>");
                cart.subscribe(function () {
                    try {
                        // if the count variable is not defined then we will not display the minicart.
                        if (count == null) {
                            count = cart().summary_count;
                            return;
                        }
                        if (cart().summary_count !== count) {
                            count = cart().summary_count;
                            var firstShowCartElement = document.getElementsByClassName('showcart')[0];
                            if (isElement(firstShowCartElement)) {
                                firstShowCartElement.click();
                                setTimeout(function() {
                                    document.body.querySelector('.minicart-modal button').click();
                                    }, (secondsToDisplay * 1000));
                            }
                        }
                    } catch (e) {
                       // intentionally ignoring this exception.
                    }
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>


