<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */

/** @var \SomethingDigital\SidebarMinicart\ViewModel\SystemConfig $viewModel */
$viewModel = $block->getSidebarMinicartViewModel();
$secondsToDisplay = $viewModel->secondsToDisplay();
$autoDisplay = $viewModel->autoDisplayEnabled();
?>

<div data-block="minicart" class="minicart-wrapper">
    <a id="minicart-show" class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'"
       onclick="dataLayer.push({'event': 'minicart_show'}); ">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
        <div class="block block-minicart empty">
            <div id="minicart-content-wrapper" class="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
        <script>
            /**
             * Checks if a variable is an HTML Element
             *
             * @param element
             * @returns {boolean}
             */
            function isElement(element) {
                return element instanceof Element || element instanceof HTMLDocument;
            }

            require(
                [
                    'jquery',
                    'jquery/ui',
                    'Magento_Ui/js/modal/modal'
                ],
                function($) {
                    var options = {
                        type: 'slide',
                        responsive: true,
                        innerScroll: false,
                        title: '',
                        buttons: [],
                        modalClass: 'minicart-modal',
                        trigger: '.minicart-wrapper .showcart',
                    };
                    $('#minicart-content-wrapper').modal(options);
                    $('.minicart-wrapper .showcart').on('click', function(e) {
                        e.preventDefault(); // prevent default behavior from redirecting customer
                    });
                    try {
                        $(document).on('ajax:addToCart', function (event, data) {
                            var displayOnAddToCart = (<?= json_encode((string)$autoDisplay) ?> === '1');
                            if (displayOnAddToCart === false) {
                                return;
                            }
                            var secondsToDisplay = parseInt(<?= json_encode((int)$secondsToDisplay) ?>, 10);
                            var showCartElements = document.getElementsByClassName('showcart');

                            if (typeof showCartElements !== 'object' && showCartElements.length === 0) {
                                return;
                            }

                            var firstShowCartElement = showCartElements[0];
                            var minicartModalElements = document.getElementsByClassName('minicart-modal');

                            if (typeof minicartModalElements !== 'object' && minicartModalElements.length === 0) {
                                return;
                            }

                            var minicart = minicartModalElements[0];

                            // Checking to see if the cart is already open.
                            if ($.inArray('_show', minicart.classList) >= 0) {
                                return;
                            }

                            if (isElement(firstShowCartElement)) {
                                firstShowCartElement.click();
                                setTimeout(function() {
                                    document.body.querySelector('.minicart-modal button[data-role="closeBtn"]').click();
                                }, (secondsToDisplay * 1000));
                            }
                        });
                    } catch (e) {
                        //
                        console.log('error', e);
                    }

                }
            );
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>


