trigger:
  batch: true
  branches:
    include:
      - feature/update-image-build
      - develop
      - master
  
pool:
  vmImage: "ubuntu-18.04"
  
stages:
- stage: ContinuousBuild
  jobs:
  - job: Docker_Build
    displayName: "Build and Push Docker images"
    steps:
    - task: Docker@2
      displayName: "Login to container registry"
      inputs:
        containerRegistry: "$(IMAGE_REGISTRY_CONNECTION)"
        command: "login"

    - task: DownloadSecureFile@1
      displayName: "Get ssh key"
      name: "github_ssh_key"
      inputs:
        secureFile: "github-deployment"
    
    - task: DownloadSecureFile@1
      displayName: "Download magento authentication file"
      name: "auth_json"
      inputs:
        secureFile: "accelerator-auth-json"
              
    - bash: mv $(Agent.TempDirectory)/accelerator-auth-json $(System.DefaultWorkingDirectory)/auth.json
      displayName: "Move auth_file to working directory"

    - bash: |
        export SSH_PRIVATE_KEY=`cat $(Agent.TempDirectory)/github-deployment`
        "$(System.DefaultWorkingDirectory)/cicd/build.sh"
      displayName: "Build Docker images"
    
    - bash: ./cicd/test.sh
      displayName: "Test Docker images"
      env:
        AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
    
    - bash: ./cicd/push.sh
      displayName: "Push Docker images"
