variables:
    IMAGE_REGISTRY: "bbsomethingdigital.azurecr.io"
    IMAGE_REGISTRY_CONNECTION: "bb-somethingdigital-dev"
      
trigger:
  batch: true
  branches:
    include:
      - feature/update-image-build
      - develop
      - master
  
pool:
  vmImage: "ubuntu-18.04"
  
stages:
- stage: ContinuousBuild
  jobs:
  - job: Docker_Build
    displayName: "Build and Push Docker images"
    steps:
    - task: Docker@2
      displayName: "Login to container registry"
      inputs:
        containerRegistry: "$(IMAGE_REGISTRY_CONNECTION)"
        command: 'login'

    - task: DownloadSecureFile@1
      displayName: "Get ssh key"
      name: 'git_ssh_key'
      inputs:
        secureFile: 'git_ssh_key'
    
    - task: DownloadSecureFile@1
      displayName: 'Download magento authentication file'
      name: 'auth_file'
      inputs:
        secureFile: 'auth.json'
              
    - bash: mv $(Agent.TempDirectory)/auth.json $(System.DefaultWorkingDirectory)/
      displayName: "Move auth_file to working directory"

    - bash: |
        export SSH_PRIVATE_KEY=`cat $(Agent.TempDirectory)/git_ssh_key`
        "$(System.DefaultWorkingDirectory)/cicd/build.sh"
      displayName: "Build Docker images"

    - script: ./cicd/push.sh
      displayName: "Push Docker images"