version: "3.6"

services:

  proxy:
    image: ${IMAGE_REGISTRY:-sdmagentodev.azurecr.io}/base-images/nginx-php-app
    restart: unless-stopped
    depends_on:
      - varnish
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./compose/env/nginx-proxy.conf:/etc/nginx/conf.d/default.conf

  varnish:
    image: varnish:6.0
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./compose/env/default.vcl:/etc/varnish/default.vcl

  app:
    image: ${IMAGE_REGISTRY:-sdmagentodev.azurecr.io}/base-images/nginx-php-app
    restart: unless-stopped
    depends_on:
      - phpfpm
    ports:
      - "8000:8000"
    volumes: &appvolumes
      - ~/.ssh:/var/www/.ssh:delegated
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - ./app/etc/env.php:/var/www/html/app/etc/env.php:delegated
      - ./compose/env/nginx-php-app.conf:/var/www/html/nginx.conf:delegated
      - sockdata:/sock

  phpfpm:
    image: ${IMAGE_REGISTRY:-sdmagentodev.azurecr.io}/${IMAGE_NAME:-animalpak}:${IMAGE_TAG:-develop}
    restart: unless-stopped
    volumes: *appvolumes
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch

  db:
    image: mariadb:10.4.11
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: compose/env/db.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./compose/files/db/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:5.0
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:6.8.6
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    expose:
      - '5672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /magento


volumes:
  appdata:
  dbdata:
  sockdata:
  rabbitmq:
