version: "3.6"

services:

  proxy:
    image: nginx-php-app:latest
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./env/nginx-proxy.conf:/etc/nginx/conf.d/default.conf

  varnish:
    image: varnish:6.0
    volumes:
      - ./env/default.vcl:/etc/varnish/default.vcl

  app:
    image: nginx-php-app:latest
    ports:
      - "8000:8000"
    volumes: &appvolumes
      - ~/.ssh:/var/www/.ssh
      - ~/.composer:/var/www/.composer:delegated
      - ../nginx.conf.sample:/var/www/html/nginx.conf:delegated
      - ../app/etc/env.php-local:/var/www/html/app/etc/env.php
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: accelerator:latest
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./files/db/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:5.0

  elasticsearch:
    image: elasticsearch:6.8.6
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq
    expose:
      - '5672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /magento

  # Disabling cron by default, enable if needed
  #cron:
  #  image: magento-php-fpm-7.2:latest
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
  rabbitmq:
